apiVersion: v1
kind: Pod
metadata:
  name: my-simple-pod
  labels:
    name: my-simple-pod
    tool: argoCD
spec:
  containers:
    - name: my-ubuntu-container
      image: ubuntu:20.04
      command:
        - 'bash'
        - '-c'
        - 'while true; do echo $(date); sleep 5; done'
